#!/bin/bash

pdfcompress ()
{
    echo "pdf compression"
	gs -q -dNOPAUSE -dBATCH -dSAFER -sDEVICE=pdfwrite -dCompatibilityLevel=1.3 -dPDFSETTINGS=/screen -dEmbedAllFonts=true -dSubsetFonts=true -dColorImageDownsampleType=/Bicubic -dColorImageResolution=144 -dGrayImageDownsampleType=/Bicubic -dGrayImageResolution=144 -dMonoImageDownsampleType=/Bicubic -dMonoImageResolution=144 -sOutputFile=$OUTPUT $INPUT;
    # gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=/data/output.pdf $1
}

INPUT="$1"
OUTPUT="$2"

echo "running compressor"
if [[ -z "$INPUT" || -z "$OUTPUT" ]]; then
  echo "Usage: $0 input.pdf output.pdf"
  exit 1
fi
pdfcompress $1 $2;